/g4sbs/filename ./output/tensor_SIDIS_g4sbs.root

/g4sbs/simcfile ./input/tensor_SIDIS_simc.root

## Configure Experiment
/g4sbs/exp             sidis

## Configure the target
/g4sbs/target          LD2
/g4sbs/targlen         15.0 cm           ## Target Length

## Configure generator settings
/g4sbs/kine            simc           ## Generator
/g4sbs/hadron          pi+         

## Configure standard detector settings
/g4sbs/hcaldist        11.0 m
/g4sbs/hcalvoffset     0.75 m
/g4sbs/beamlineconfig  3                 ## set relevant beamline configuration
/g4sbs/sbsclampopt     3                 ## Front field clamp only

## Configure the magnets
/g4sbs/bbfield         1
/g4sbs/scalebbfield    0.9672 
/g4sbs/tosfield        SBSPortableFieldMap_FrontClampOnly_NoPoleShims.table 2
/g4sbs/scalesbsfield   0.390
/g4sbs/bbang           36.0 deg
/g4sbs/bbdist          1.7988 m
/g4sbs/sbsang          31.9 deg
/g4sbs/48D48dist       2.25 m 

## Al bg shielding in front of the scattering chamber
/g4sbs/setbigbiteplate      0           ## ON for SBS11,14,8,9
/g4sbs/bigbiteplatethick    0.3175 cm   ## 1/8 in
/g4sbs/bigbiteplatematerial Al

/g4sbs/keepsdtrackinfo 	all true
/g4sbs/totalabs true

## Run 1000 events
/g4sbs/eventstatusevery 1000
#/g4sbs/run             10000
